[[redirects]]

from = "/"
to = "/"
status = 200
force = false
query = {path = "/"}

from = "/about"
to = "/about"
status = 200
force = false
query = {path = "/about"}

from = "/projects"
to = "/projects"
status = 200
force = false
query = {path = "/projects"}